
export const projectArray = [
  { image: '../../assets/plantmama.png',
    title: 'PlantMama',
    description: 'PlantMama is an end to end web application I coded with a MongoDB database, a React frontend with Redux store and a NodeJS backend; hosted on Google Cloud. It provides user authentication and integrates with a third party API. It is continuously deployed on Netlify and GCP.',
    tags: ['React', 'Express', 'Node', 'MongoDB', 'GoogleCloud'],
    githubLink: 'PlantMAMA-frontend',
    netlifyLink: 'plantmama' },

  { image: '../../assets/labyrinth.png',
    title: 'Maze Runner Game',
    description: 'An interactive game where the user needs to find the way out of a labyrinth.',
    tags: ['React', 'Redux', 'APIs', 'HTML5', 'CSS3'],
    githubLink: 'project-labyrinth',
    netlifyLink: 'liongroupmazerunner' },

  { image: '../../assets/todo.png',
    title: 'To-Do App',
    description: 'Designed and built a to-do app with Redux by creating slices, reducers and actions from scratch.',
    tags: ['React', 'Redux', 'HTML5', ' CSS3'],
    githubLink: 'project-todos',
    netlifyLink: 'plantastic-to-do' },

  { image: '../../assets/movies.png',
    title: 'Movies',
    description: 'Browse popular movies and series. Built using hooks and routes in React with the use of APIs.',
    tags: ['Router', 'Hooks', 'APIs', 'HTML5', 'CSS3'],
    githubLink: 'project-movies',
    netlifyLink: 'quiet-movies' },

  { image: '../../assets/quiz.png',
    title: 'Quiz using Redux',
    description: 'A multiple-choice quiz with Redux, the assignment was to interact with the store using selectors and dispatching actions. This was my first project in Redux.',
    tags: ['React', 'Redux', 'HTML5', 'CSS3 '],
    githubLink: 'project-redux-quiz',
    netlifyLink: 'quiz-about-react' },

  { image: '../../assets/survey.png',
    title: 'Survey',
    description: 'A survey design and created a Fun Typeform-like product using React state and controlled form.',
    tags: ['React', 'JSX', 'Javascript', 'HTML5', 'CSS3 '],
    githubLink: 'project-survey',
    netlifyLink: 'zombie-survey' },

  { image: '../../assets/happy.png',
    title: 'Happy Thoughts chat',
    description: 'A live chatboard where you can post happy thoughts, built in React using APIs',
    tags: ['React Hooks', 'APIs', 'HTML5', 'CSS3'],
    githubLink: 'project-happy-thoughts',
    netlifyLink: 'happy-thoughtss' },

  { image: '../../assets/music.png',
    title: 'Music Releases',
    description: 'A responsive music site showing new releases and popular artists using APIs. This was my first project in React.',
    tags: ['APIs', 'Javascript ES6', 'HTML5', 'CSS3'],
    githubLink: 'project-music-releases',
    netlifyLink: 'heartfelt-music' },

  { image: '../../assets/weather.png',
    title: 'Weather App',
    description: 'Followed a design and built a simple weather dashboard that tells todays weather, temperature and a 5-day forecast using a weather API.',
    tags: ['APIs', 'Javascript', 'CSS3', 'Pair Programming'],
    githubLink: 'project-weather-app',
    netlifyLink: 'app-for-forecast' },

  { image: '../../assets/guesswho.png',
    title: 'Guess who the game',
    description: 'A digital version of the classic board game Guess who.',
    tags: ['Javascript ES6', 'HTML5', 'CSS3'],
    githubLink: 'project-guess-who',
    netlifyLink: 'indovina-chi' },

  { image: '../../assets/chatbot.png',
    title: 'Chatbot',
    description: 'Chatbot built in Javascript.',
    tags: ['Javascript ES6', 'HTML5', 'CSS3'],
    githubLink: 'project-chatbot',
    netlifyLink: 'cookies-chatbot' }
]